services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: qwik-webapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ORIGIN=http://localhost
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    command: ["npm", "run", "start"]

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: laravel-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: posgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
